server:
  port: 34621
  
spring:
  application:
    name: forca
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
      
  datasource:
    url: ${JDBC_DATASOURCE_URL}
    
  flyway:
    enabled: true
    url: ${JDBC_DATASOURCE_URL}
    locations: classpath:db/migration
    
logging:
  level:
    org.hibernate.type: trace