server:
  port: 34621
  
spring:
  application:
    name: forca
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
      
  datasource:
    url: jdbc:${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    
  flyway:
    enabled: true
    url: jdbc:${JDBC_DATABASE_URL}
    user: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    locations: classpath:db/migration
    
logging:
  level:
    org.hibernate.type: trace