server:
  port: 34621
  
spring:
  application:
    name: forca
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
      
  datasource:
    url: ${JDBC_DATASOURCE_URL}
    
  flyway:
    enabled: true
    url: jdbc:mysql://us-cdbr-iron-east-05.cleardb.net/heroku_a1dd069016e3708
    user: b1b983fabbca16
    password: 1b93a38c
    locations: classpath:db/migration
    
logging:
  level:
    org.hibernate.type: trace